version: '3.8'

services:
  api-gateway:
    image: ${IMAGE_URL}
    build: .
    container_name: ${CONTAINER}
    restart: unless-stopped
    env_file: "envs/.env.local.yml"
    volumes:
      - ./kong-mnt:/home/kong/kong-mnt:rw
    ports:
      - ${TARGET_LOCAL_PORT}:${TARGET_REMOTE_PORT}/tcp
      - "8001:8001/tcp"
      - "8443:8443/tcp"
      - "8444:8444/tcp"
