DEBUG=${DEBUG}
GOOGLE_CLOUD_PROJECT=${TARGET_PROJECT_ID}
GOOGLE_APPLICATION_CREDENTIALS=/secrets/fb-admin-credentials.json
LOGS=${LOGS}
LOCAL_PORT=${TARGET_LOCAL_PORT}
REMOTE_PORT=${TARGET_REMOTE_PORT}
SERVICE=${SERVICE}
TITLE=${TITLE}
TZ=America/Denver
KONG_ADMIN_ACCESS_LOG=/dev/stdout
KONG_ADMIN_ERROR_LOG=/dev/stderr
KONG_ADMIN_LISTEN=0.0.0.0:8001
KONG_DATABASE=off
KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
KONG_PROXY_ACCESS_LOG=/dev/stdout
KONG_PROXY_ERROR_LOG=/dev/stderr
KONG_LOG_LEVEL=${TARGET_LOG_LEVEL}
KONG_ROLE=control_plane
KONG_CLUSTER_CERT=/cluster/cert/cluster.crt
KONG_CLUSTER_CERT_KEY=/cluster/cert/cluster.key
KONG_CLUSTER_LISTEN=0.0.0.0:8005
KONG_CLUSTER_TELEMETRY_LISTEN=0.0.0.0:8006
